import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import WrapperComponent from './WrapperComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Youtube Next App',
  description: 'Generated by Dan Tech Services'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <WrapperComponent>{children}</WrapperComponent>
      </body>
    </html>
  )
}
